### ISSUE TITLE
IMDB id is edb://

### ISSUE THREAD

**Issue by tf2manu994** [ukdtom/plex2csv.bundle#103]
Not in tt format

**Comment by ukdtom** [comment]
Huh.....

Returns tt<number> AFAICT

**Comment by tf2manu994** [comment]
Mine has edb...

**Comment by ukdtom** [comment]
I'll need a log and a snip of an csv file, and please also extend your comments here a tad, so I don't have to guess all the time ;-)

**Comment by ukdtom** [comment]
Closing due to lack of response
