### ISSUE TITLE
Export of TV Series Collections

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#105]
Would it be possible to add the Collections from TV series to one of the export levels as it is available for Movies on export level 3?

**Comment by ukdtom** [comment]
Added Collections and Locked fields to TV-Show level 2 and above

Please test, and report back here

And download here:

[https://github.com/ukdtom/plex2csv.bundle/archive/tommy-work.zip](url)

**Comment by SvenErik1968** [comment]
Tried an export with level 2, and both Collections and Locked fields were included in the csv file, so it looks like it works as it should! 

Thanks! :D

**Comment by ukdtom** [comment]
Thanks for the feedback, and released
