### ISSUE TITLE
include the `guid` like for movies

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/plex2csv.bundle#113]
Currently, we can export the `guid` for movies, so we can easily extract the IMDB ID or the TheMovieDB ID. (or can even tell if a movie is unmatched).

The same should be possible for tv show episodes.

**Comment by ukdtom** [comment]
Getting old here? :-P

Check this one out:
https://github.com/ukdtom/plex2csv.bundle/issues/107

Also check the changelog in that

As well as the tommy-work branch, and do report back ;-)
