### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by guptaravi** [ukdtom/plex2csv.bundle#115]
Hi

I am trying to use this awesome application to export the codec information from my Plex library. The size of the library is about 12 TB. When clicking the export option, the operation simply fails.

**Comment by ukdtom** [comment]
I need logs

**Comment by guptaravi** [comment]
How do I provide the logs? Anything listing the steps would be great. Thanks.

**Comment by ukdtom** [comment]
https://github.com/ukdtom/plex2csv.bundle/wiki/Troble-Shooting

**Comment by guptaravi** [comment]
[Plex2CSVLogs.zip](https://github.com/ukdtom/plex2csv.bundle/files/324423/Plex2CSVLogs.zip)

Attaching logs. Thanks for looking into it.

**Comment by ukdtom** [comment]
Make sure, that the user used to run your PMS, has full rights to this directory:

`  File "/Users/admin/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-bbb376f/lib/python2.7/os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/Volumes/MovieLib01/plex2csv'`

**Comment by guptaravi** [comment]
Thanks. Explicitly adding read and write permissions to the external drive fixed the issue.
