### ISSUE TITLE
Inconsistent date formats

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#117]
I just noticed that the **Release Date** uses ISO 8601 date format _YYYY-MM-DD_ while the **Added** and **Updated** field uses the US format _MM/DD/YYYY_.

Example:

    "Media ID","Title","Sort title","Studio","Content Rating","Year","Rating","Summary","Genres","View Count","Last Viewed at","Tagline","Release Date","Writers","Country","Duration","Directors","Roles","Labels","Locked Fields","Extras","Collections","Original Title","Added","Updated","Audio Languages","Audio Title","Subtitle Languages","Subtitle Title","Subtitle Codec","Accessible","Exists","MetaDB Link","Poster url","Art url","Video Resolution","Bitrate","Width","Height","Aspect Ratio","Audio Channels","Audio Codec","Video Codec","Container","Video FrameRate","Part File","Part Size","Part Indexed","Part Duration","Part Container","Part Optimized for Streaming"
    "2229","The 'High Sign'","'High Sign'","Joseph M. Schenck Productions","N/A","1921","5.7","Buster is thrown off a train near an amusement park. There he gets a job in a shooting gallery run by the Blinking Buzzards mob. Ordered to kill a businessman, he winds up protecting the man and his daughter by outfitting their home with trick devices.","Crime - Comedy","N/A","N/A","What A Predicament!","1921-04-18","Edward F. Cline - Buster Keaton","USA","0:20:37","Edward F. Cline - Buster Keaton","Buster Keaton - Bartine Burkett - Charles Dorety - Joe Roberts - Al St. John - Ingram B. Pickett","","","0","","N/A","05/16/2016","06/20/2016","eng","N/A","","","","N/A","N/A","https://www.themoviedb.org/movie/46510","/library/metadata/2229/thumb/1466409108","/library/metadata/2229/art/1466409108","480","1510","652","514","1.33","2","aac","h264","mkv","PAL","\\DISKSTATION2\Film\1920s\The High Sign (1921)\The High Sign (1921).mkv","0.22 GB","N/A","0:20:37","mkv","N/A"

I suggest that the export of the  **Added** and **Updated** fields get changed to use ISO 8601 format.

**Comment by ukdtom** [comment]
Care to test the tommy-work branch?
And then report back, please

**Comment by SvenErik1968** [comment]
Works like a charm! :D 

```
"Media ID","Title","Sort title","Studio","Content Rating","Year","Rating","Summary","Genres","View Count","Last Viewed at","Tagline","Release Date","Writers","Country","Duration","Directors","Roles","Labels","Locked Fields","Extras","Collections","Original Title","Added","Updated","Audio Languages","Audio Title","Subtitle Languages","Subtitle Title","Subtitle Codec","Accessible","Exists","MetaDB Link","Poster url","Art url","Video Resolution","Bitrate","Width","Height","Aspect Ratio","Audio Channels","Audio Codec","Video Codec","Container","Video FrameRate","Part File","Part Size","Part Indexed","Part Duration","Part Container","Part Optimized for Streaming"
"2229","The 'High Sign'","'High Sign'","Joseph M. Schenck Productions","N/A","1921","5.7","Buster is thrown off a train near an amusement park. There he gets a job in a shooting gallery run by the Blinking Buzzards mob. Ordered to kill a businessman, he winds up protecting the man and his daughter by outfitting their home with trick devices.","Crime - Comedy","N/A","N/A","What A Predicament!","1921-04-18","Edward F. Cline - Buster Keaton","USA","0:20:37","Edward F. Cline - Buster Keaton","Buster Keaton - Bartine Burkett - Charles Dorety - Joe Roberts - Al St. John - Ingram B. Pickett","","","0","","N/A","2016-05-16","2016-06-20","eng","N/A","","","","N/A","N/A","https://www.themoviedb.org/movie/46510","/library/metadata/2229/thumb/1466409108","/library/metadata/2229/art/1466409108","480","1510","652","514","1.33","2","aac","h264","mkv","PAL","\\DISKSTATION2\Film\1920s\The High Sign (1921)\The High Sign (1921).mkv","0.22 GB","N/A","0:20:37","mkv","N/A"
"1686","The 'Maggie'","'Maggie'","Ealing Studios","Passed","1954","5.4","The poor, elderly,.....and wily when it comes to parting those who can afford it from their money.....Scottish skipper of a broken-down old 'puffer' boat (Alex Mackenzie) tricks an American tycoon into paying him to transport his personal cargo. When the aforementioned tycoon (Paul Douglas) learns of the trick, he attempts to track down the boat and remove his possessions.  Released in the United States as ""High and Dry"".","Comedy","N/A","N/A","N/A","1954-02-25","William Rose","United Kingdom","1:32:04","Alexander Mackendrick","Paul Douglas - Alex Mackenzie - James Copeland - Abe Barker - Tommy Kearins - Hubert Gregg","","","0","","N/A","2016-05-16","2016-06-20","eng","N/A","eng","N/A","srt","N/A","N/A","https://www.themoviedb.org/movie/48954","/library/metadata/1686/thumb/1466406756","/library/metadata/1686/art/1466406756","1080","2224","1472","1080","1.33","2","aac","h264","mkv","24p","\\DISKSTATION2\Film\1950s\The 'Maggie' (1954)\The 'Maggie' (1954).mkv","1.43 GB","N/A","1:32:04","mkv","N/A"
```

**Comment by ukdtom** [comment]
Thanks
