### ISSUE TITLE
UTF8 File path/names

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#121]
I have some Thai movies in my database, and for a couple of those, I only have the film name in Thai.
For the export of those movies, the title and description in Thai comes out OK, but not the path/filename

Examples from a Level 5 Movie export:
```
"2733","เรียม 1","N/A","N/A","N/A","1991","N/A","","","N/A","N/A","N/A","N/A","","","3:03:17","","","","","0","","N/A","2016-03-27","2016-07-11","tha","N/A","","","","N/A","N/A","N/A","/library/metadata/2733/thumb/1468217760","/library/metadata/2733/art/1468217760","sd","1574","352","288","1.33","2","aac","h264","mkv","PAL","\\DISKSTATION2\Film\1990s\%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%A1 1 (1991)\%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%A1 1 (1991).mkv","2.02 GB","N/A","3:03:17","mkv","N/A"
"19974","เรียม 3 (1992)","N/A","N/A","N/A","2016","N/A","","","N/A","N/A","N/A","2016-03-27","","","1:33:02","","","","","0","","N/A","2016-03-27","2016-07-11","tha","N/A","","","","N/A","N/A","N/A","/library/metadata/19974/thumb/1468217761","/library/metadata/19974/art/1468217761","sd","940","352","288","1.33","2","aac","h264","mkv","PAL","\\DISKSTATION2\Film\1990s\%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%A1 3 (1992)\%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%A1 3 (1992).mkv","0.61 GB","N/A","1:33:02","mkv","N/A"
```
The correct path/file names should be:
```
\\DISKSTATION2\Film\1990s\เรียม 1 (1991)\เรียม 1 (1991).mkv
\\DISKSTATION2\Film\1990s\เรียม 3 (1992)\เรียม 3 (1992).mkv
```
Is this something you could get fixed so the exported path would make more sense for a human? :)

**Comment by SvenErik1968** [comment]
I am also seeing this issue with Norwegian vowels

`"4142","... men Olsenbanden var ikke død!","... men Olsenbanden var ikke d0d!","Teamfilm AS","N/A","1984","6.2","Hvordan gikk det egentlig med Egon, Benny og Kjell i Olsenbanden, som i siste film dro sydover med kofferten full av panger? Svaret får vi nå!","Comedy","N/A","N/A","N/A","1984-09-06","Knut Bohwim - Gustav Kramer","Norway","1:26:03","Knut Bohwim","Arve Opsahl - Carsten Byhring - Sverre Holm - Aud Schønemann - Sverre Wilberg - Jon Skolmen - Knut Lystad - Harald Heide-Steen Jr.","","","0","Olsenbanden","N/A","2015-11-01","2016-07-11","nor","N/A","","","","N/A","N/A","https://www.themoviedb.org/movie/24699","/library/metadata/4142/thumb/1468188115","/library/metadata/4142/art/1468188115","sd","1079","608","352","1.78","2","aac","h264","mkv","PAL","\\DISKSTATION2\Film\1980s\Men Olsenbanden var ikke d%C3%B8d (1984)\Men Olsenbanden var ikke d%C3%B8d (1984).mkv","0.65 GB","N/A","1:26:03","mkv","N/A"`

And it should be:
`\\DISKSTATION2\Film\1980s\Men Olsenbanden var ikke død (1984)\Men Olsenbanden var ikke død (1984).mkv`

**Comment by ukdtom** [comment]
Norwegian vowels are of no concern to me, but to my horror, I found that Danish vowels was broken ;-)

Output after I hopefully fixed it is:
``` "/share/CACHEDEV1_DATA/video/movies/Comedy/Olsen-Banden/Olsen-banden Går Amok (1973).blueray-1.mkv" ```

Hopefully fixed with https://github.com/ukdtom/plex2csv.bundle/commit/0daba9eaa1fc6dc9ccd126692979341d4036b55e

So please try the Tommy-Work branch, and then report back

/T

**Comment by SvenErik1968** [comment]
Tested and it works like a charm now! :+1: #
Thanks and have a great weekend! :D

**Comment by ukdtom** [comment]
Merged into master, and FUI:
https://forums.plex.tv/discussion/comment/1218224/#Comment_1218224

**Comment by SvenErik1968** [comment]
Thanks! I saw that in the change log for the Tommy-Work branch ;-)
