### ISSUE TITLE
Feature Request: Consistent & Numerical Value for Size

### ISSUE THREAD

**Issue by chansearrington** [ukdtom/plex2csv.bundle#126]
Currently the export for movies shows "2.36 GB" or "349 MB" but this is problematic when you want to use these values as numbers in Excel.

I understand that this used to be implemented as solely GB, and that would help, but would like just a number as well so that I can see what the total storage need is for X selected items.

**Comment by SvenErik1968** [comment]
I agree, it would be useful to also have the size in bytes for when you need to do file-size calculations.

**Comment by ukdtom** [comment]
I hate you guys :-P

And turned into an RFE

**Comment by ukdtom** [comment]
Fix checked in https://github.com/ukdtom/plex2csv.bundle/commit/858ad676b61da8a71eab59344df3eba699878d2f

Please betatest the tommy-work branch, and report back
See the changelog file for details

**Comment by rabelux** [comment]
Works fine on movie exports for me :+1:

**Comment by SvenErik1968** [comment]
I concur, this works with me too.

**Comment by ukdtom** [comment]
In that case I close this one, and it'll be in the next published version.

Thanks guys
