### ISSUE TITLE
feature: output movies that are available in netflix

### ISSUE THREAD

**Issue by geogolem** [ukdtom/plex2csv.bundle#138]
So I have this use-case.. Sometimes I want to go through my library and see which of the movies in my library are available in netflix.

To accomplish this, I used plex2csv and then I opened the output of plex2csv within a python script, which then checks if each movie exists in netflix. 

I have no issues - doing this manually (i.e. runing plex2csv) and then running my script using the output from plex2csv and seeing the results.. but I think it would be nice to run this without the need to actually load up the commandline and move around the output files etc.

I thought I about making my own plugin ---> plexNetflixChecker or something..
but I havent had the chance or been able to find decent enough info to figure out how to actually build my own plugin from scratch...

Im just posting here because this might be something you could integrate easily into plex2csv. If I provided a python script that takes the output from plex2csv does the look up and outputs to stdout what it finds -- would it be easy to integrate this into plex2csv as an additional button you click, does the lookup and then displays the info within plex itself? (not displaying in the library - I just mean some text output like title (year) matched with title (year in netflix)...

I know netflix doesnt have an API. but i check allflicks.net

**Comment by ukdtom** [comment]
That would be out of scope for Plex2CSV, and not going to let it req. from external sources.
Sorry
