### ISSUE TITLE
Include path to file(s) in output?

### ISSUE THREAD

**Issue by Mushin** [ukdtom/plex2csv.bundle#150]
Hi, I was wondering if it would be possible to include the path to the associated file(s) for each item in the exported csv?

**Comment by ukdtom** [comment]
For like movies, we have the field Part File for level 5, if that's what you are talking about?

**Comment by ukdtom** [comment]
https://github.com/ukdtom/plex2csv.bundle/wiki/Movie-Export-Level

**Comment by Mushin** [comment]
Oh, I hadn't seen that part of the Wiki. Thanks for the info and sorry for the redundant question!

**Comment by ukdtom** [comment]
NP
