### ISSUE TITLE
Allow remaining Library Categories to be exported

### ISSUE THREAD

**Issue by sa2000a** [ukdtom/plex2csv.bundle#50]
Please look into allowing export of Photos library categories plus any other remaining category so that this tool becomes a true plex 2 csv utility

Thank you

**Comment by ukdtom** [comment]
Hmm.....Since Photo's can be nested in different directory levels, this is going to be kinda tricky :-(

**Comment by ukdtom** [comment]
Should be there, when 0.0.4.2 is released
