### ISSUE TITLE
BUG: upon opening plex2csv it takes me to mainmenu if scan is going (but should take to current scan instead)

### ISSUE THREAD

**Issue by kossboss** [ukdtom/plex2csv.bundle#56]
BUG:
When clicking on the plex2csv from Channels while a scan is going, it takes me to main menu - it should take me to current scan progress page instead (am i correct? or are you implementing ability to do simultaneous scans?) - I assume that your only allowing 1 scan per any moment - so with that logic if there is a scan going on, when you enter plex2csv it should NOT take you to the mainmenu (where you can launch a new scan) it should take you to scan progress page instead.

CURRENT WORKAROUND: Workaround is to click on an item (as if you wanted to scan the said item) in main menu and it will show me current scan progress instead of starting another scan

Another thing you can do is in the main menu have a button "stop current scan" if there is a scan ongoing and "view current scan progress" if there is a scan ongoing.

**Comment by ukdtom** [comment]
Don't think that's possible with the framework
