### ISSUE TITLE
BUG: urllib2

### ISSUE THREAD

**Issue by kossboss** [ukdtom/plex2csv.bundle#58]
-- One more attempt --
Can you please fix the URLLIB2 bug?
And dont close the bug on an unsolved issue.

**Comment by ukdtom** [comment]
Then provide me whit what I need, instead of saying you know better.
And if you do know better, then fork, fix and create a Pull Req.

**Comment by kossboss** [comment]
Ill send you the logs, let me know how.

**Comment by ukdtom** [comment]
https://github.com/ukdtom/plex2csv.bundle/wiki/Troble-Shooting

**Comment by kossboss** [comment]
Here you go:
http://wikisend.com/download/679874/plex2csv-logs.7z
PW to download: githubmadness123
dl only avail for 90 days

---

I already found out why the problem is happening, I just dont know python enough to fix it. I can figure it out but it will take you much less time.

I can clearly see the issue without the FULL logs. I can look at the last line that says urlib2 error (which by the way is the only error in the whole log). then I look that up in google. It mentions port exhaustion. Its because you close() your urllib2 open & requests statements, so ports got exhausted, simple - I just cant implemented it - I tried my shit fails. And the port exhaustion is true. If I open up cygwin and monitor ports check this out:

while true; do echo "total: `netstat -n | wc -l` plex: `netstat -n | grep 32400 | wc -l`"; sleep 1; done

We see that once your plex2csv plug in starts scanning we grow from 100 connection base (lets assume that at least) to 800 then to 1200 then 1500 and mine stablized at 1600. Once plex2csv closed it went down to like 400 then finally back to 100. It takes a minute to lower to 100. So while its up there in the 1600, if I try another scan (even if one is finished), the error will come up and scan will fail

My Plex INFO:
SERVER: Windows 8.1
Most of the my movies and tvshows are on a ReadyNAS Pro 6 NAS
Some videos are local (on an attached E drive but MOST are on the NAS
The database for plex is kept locally on the Windows 8.1 machine. I have a C local drive and D local drive. C is SSD. D is SATA. S drive is the NAS (samba mount)

**Comment by ukdtom** [comment]
tommy-work branch now use paged requests, if exporting a movie section only.
This might fix the issue.
Work ToDo is to add this to export of Audio and TV-Shows as well

**Comment by kossboss** [comment]
Awesome! I will try it when I get home. Just let me know when its okay to grab a copy of tommy-work, I see that your in the middle of working on it (with updates being 8 minutes ago).

Also in find-missing, I noticed a discussion about my plex library possibly being curropt. I dont think it is as this plex2csv pluggin completes all the way sometimes, just not always. I came across a bandwidth manager a few months ago, that I just uninstalled that might of fixed the issue its called "netbalancer" but it could of possibly been slowing down the connections, and thus many more were staying open thus creating the crazy rain of connections and eventaully that urllib2 bug came out of the blue.

I have uninstalled "netbalancer" - which increased my Explorer to Samba on the NAS connections from 3MBPS to 30-50 MBP - I told netbalancer to prioritize "plex" but who knows if it really did, that "netbalancer" was kinda of buggy with its latest update. When I get home, I will test with plex2csv (current stable) and with tommy-work version (once you okay when its cool to download it).

**Comment by ukdtom** [comment]
Go ahead now, but note that only movie sections are updated to use paging.

Other sections use the "old" way

**Comment by ukdtom** [comment]
So...Did it help?

**Comment by kossboss** [comment]
testing now.

(first test) running regular stable version 0.0.2.7 for movies and tv on most extereme (running from home  with plextv auth). I see my netstat connections skyrocket:
total is # of netstat connections, plex is number of netstat connections on port 32400. interval 1 second. note I have 1554 movies in this set.
right when i started it:
total: 438, plex: 255
total: 436, plex: 255
total: 434, plex: 254
total: 435, plex: 254
total: 428, plex: 254
after a few minutes:
total: 2968, plex: 2574
total: 2994, plex: 2606
total: 3025, plex: 2643
total: 3072, plex: 2694
total: 3122, plex: 2742
total: 3162, plex: 2785
total: 3210, plex: 2814
total: 3260, plex: 2857
total: 3300, plex: 2892
total: 3342, plex: 2932
total: 3341, plex: 2932
total: 3369, plex: 2971
total: 3419, plex: 3020
total: 3414, plex: 2995
total: 3427, plex: 3020
after its finished (no fail, no errors):
total: 1243, plex: 1023
total: 1259, plex: 1041
total: 1251, plex: 1027
total: 1221, plex: 987
total: 1192, plex: 979
total: 1191, plex: 980
total: 1156, plex: 941
ran it again on movies and it bumped all the way up. but no fail no errors
(test2) Running on stable version, tv shows.
69 tv shows. it goes up to this:
total: 3988, plex: 3810
total: 4077, plex: 3900
total: 4136, plex: 3920
total: 4163, plex: 3999
total: 4209, plex: 4036
total: 4195, plex: 4030
total: 4235, plex: 4065
total: 4302, plex: 4097
total: 4337, plex: 4168
total: 4415, plex: 4238
total: 4455, plex: 4271
total: 4520, plex: 4341
RESULTS) now everything works without failing on the stable version of plex2csv (ver  0.0.2.7). I didnt even need to try the tommy-work one. it looks like the urlib error was happening due to netbalancer slowing down my samba to 3mbps or less. Now im actually able to see more netstat connections without it failing.

For the hell of it trying tommy-work) 0.0.2.8dev2
Movie test) It runs without issue.
total: 277, plex: 80
total: 278, plex: 80
total: 277, plex: 80
total: 274, plex: 80
total: 274, plex: 80
total: 274, plex: 80
total: 271, plex: 79
total: 271, plex: 79
total: 267, plex: 78
total: 267, plex: 78
total: 262, plex: 78
total: 259, plex: 78
total: 260, plex: 78
total: 257, plex: 78
total: 255, plex: 78
total: 254, plex: 78
total: 261, plex: 82
total: 263, plex: 82
total: 267, plex: 82
total: 270, plex: 82
total: 267, plex: 82
total: 270, plex: 79
total: 266, plex: 79
total: 269, plex: 79
total: 269, plex: 79
total: 268, plex: 79
total: 268, plex: 79
total: 270, plex: 79
total: 269, plex: 79
total: 270, plex: 79
total: 273, plex: 79
total: 271, plex: 79
total: 272, plex: 79
total: 283, plex: 87
total: 312, plex: 111
total: 344, plex: 152
total: 392, plex: 201
total: 432, plex: 238
total: 471, plex: 281
total: 498, plex: 312
total: 552, plex: 364
total: 601, plex: 410
total: 618, plex: 420
total: 622, plex: 423
total: 652, plex: 461
total: 685, plex: 496
total: 689, plex: 496
total: 712, plex: 519
total: 755, plex: 561
total: 805, plex: 605
total: 866, plex: 663
total: 923, plex: 715
total: 979, plex: 772
total: 1038, plex: 826
total: 1065, plex: 849
total: 1119, plex: 898
total: 1131, plex: 915
total: 1149, plex: 931
total: 1178, plex: 966
total: 1214, plex: 996
total: 1269, plex: 1054
total: 1293, plex: 1082
total: 1332, plex: 1124
total: 1373, plex: 1161
total: 1406, plex: 1195
total: 1446, plex: 1234
total: 1490, plex: 1281
total: 1542, plex: 1331
total: 1590, plex: 1373
total: 1638, plex: 1422
total: 1682, plex: 1463
total: 1722, plex: 1505
total: 1772, plex: 1552
total: 1820, plex: 1603
total: 1864, plex: 1649
total: 1901, plex: 1695
total: 1937, plex: 1731
total: 1960, plex: 1739
total: 1971, plex: 1760
total: 1994, plex: 1790
total: 2030, plex: 1829
total: 2063, plex: 1867
total: 2101, plex: 1905
total: 2154, plex: 1957
total: 2191, plex: 1988
total: 2220, plex: 2018
total: 2239, plex: 2040
total: 2267, plex: 2065
total: 2274, plex: 2080
total: 2318, plex: 2126
total: 2354, plex: 2153
total: 2399, plex: 2215
total: 2469, plex: 2277
total: 2495, plex: 2300
total: 2531, plex: 2330
total: 2573, plex: 2378
total: 2630, plex: 2427
total: 2673, plex: 2479
total: 2707, plex: 2510
total: 2749, plex: 2556
total: 2790, plex: 2595
total: 2822, plex: 2621
total: 2820, plex: 2623
total: 2869, plex: 2678
total: 2914, plex: 2714
total: 2940, plex: 2749
total: 2995, plex: 2803
total: 3052, plex: 2859
total: 3099, plex: 2905
total: 3140, plex: 2946
total: 3190, plex: 2997
total: 3244, plex: 3045
total: 3295, plex: 3098
total: 3332, plex: 3132
total: 3395, plex: 3189
total: 3454, plex: 3248
total: 3509, plex: 3299
total: 3517, plex: 3300
total: 3516, plex: 3300
total: 3518, plex: 3300
total: 3518, plex: 3300
total: 3500, plex: 3272
total: 3459, plex: 3243
total: 3420, plex: 3204
total: 3361, plex: 3147
total: 3326, plex: 3113
The end, now its going down with connections numberss
total: 3299, plex: 3085
total: 3241, plex: 3028
total: 3210, plex: 2997
total: 3179, plex: 2965
total: 3176, plex: 2963

Both now run without issue. It looks like connection numbers with netstat are high with tommy-work and with stable-version, but that was probably not the issue. The issue was netbalancer.

We can close the case. Its up to you if you want to include the new algorithm to request movie info.

**Comment by ukdtom** [comment]
It's not just to fix your issue I went down that road ;-)
