### ISSUE TITLE
IMDB Id

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/plex2csv.bundle#64]
Include IMDB ID when exporting Movies.

Investigate if also possible for Shows, and if so, also do it there

**Comment by vanstinator** [comment]
+1 :)

**Comment by ukdtom** [comment]
Fixed, but not yet released into public

**Comment by vanstinator** [comment]
Awesome :)

**Comment by ukdtom** [comment]
You can try a beta of it here

https://github.com/ukdtom/plex2csv.bundle/archive/tommy-work.zip

And Shows doesn't have IMDB Id

**Comment by vanstinator** [comment]
Awesome. I was going to ask if you could give me a beta bundle, or even
just the raw python. I've got some script ideas to try after work using
this. Thanks!

**Comment by ukdtom** [comment]
Do report back, since I'm very close to release

**Comment by vanstinator** [comment]
Getting an error, not sure what is causing it. I'll post my log shortly if
I continue to have issues.

**Comment by vanstinator** [comment]
https://www.dropbox.com/s/7coz97wcz60ixii/Plex%20Media%20Server.log?dl=0

**Comment by vanstinator** [comment]
Ok so when I click on Movies to generate it will create a file with the column headings and then fail. The UI tells me to check the logs. I can send over the settings I have setup too if you want.

**Comment by ukdtom** [comment]
Not a public download ;-)

Feel free to send it in a PM on the forums to dane22

/T

**Comment by vanstinator** [comment]
Sigh. I miss the old days of the straight up public folder. I'll PM ya

**Comment by ukdtom** [comment]
Fixed in version 0.0.2.8
