### ISSUE TITLE
Exporting the movie "Country" fields

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#76]
Would it be possible to add the Movie Country field to one of the export levels?

![plexmoviecountry](https://cloud.githubusercontent.com/assets/10983802/9928152/59b751bc-5d24-11e5-8a6b-1ccf24946fd1.jpg)

**Comment by ukdtom** [comment]
Slated for next version. Code done ;-)

**Comment by SvenErik1968** [comment]
Great! And thanks for this very useful tool that plex2csv is!
