### ISSUE TITLE
Managed Users not updating watched count

### ISSUE THREAD

**Issue by bandgeekbilly824** [ukdtom/plex2csv.bundle#84]
Not sure if anyone has run into this or it has already been brought up.
I love the plugin and it works great.
I have several managed users on my account with plex pass and when we watch movies on the main account the view count increases but if say my son watches a movie on his account it doesn't change.
I tried to run the channel on his account but I get the same result as if I was running it on the main account.
Is there a way to get all the accounts view count stats mixed into one or is there a way so if I run it under his name it will only show the results of his username?
Thanks and keep up the good work.

**Comment by ukdtom** [comment]
This plugin is regarding media data, and not individual users view count.

When accessing a media, this info is not avail, so simply can't report that

/T
