### ISSUE TITLE
Internal Errors on export of movies and TV Shows - version 0.0.4.2

### ISSUE THREAD

**Issue by sa2000a** [ukdtom/plex2csv.bundle#90]
Log file here  https://gist.github.com/sa2000a/e90e266368b46cc37e42
Screenshot 
![plex2csv_v0 0 4 2_internal error on export movie and tv shows libraries](https://cloud.githubusercontent.com/assets/6320013/11199309/57fe36cc-8cc4-11e5-8f95-9c52100f8147.jpg)

**Comment by ukdtom** [comment]
Hmmm......From the log:

D:\MediaUploads\Photos\Plex2csv\PhotoUploads--20151117-000834.csv

Should have been: D:\MediaUploads\Photos\Plex2csv\PhotoUploads-EXPORTLEVEL-20151117-000834.csv

So please confirm in the prefs, that you did select a level, and if so, what level?

**Comment by ukdtom** [comment]
And disregard above.....I do see a bug here....SIGH....

**Comment by ukdtom** [comment]
Please redownload from tommy-work branch, and try again

**Comment by ukdtom** [comment]
Fixed
