### ISSUE TITLE
Feature Request: User defined export levels

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#94]
Would it be possible to create user defined export levels (one per library type) where you can pre-define the elements and order in a configuration file stored on the server?

**Comment by ukdtom** [comment]
It been considered, but currently not possible, due to the limited GUI in the Plex Channels framework.

In the future, I might migrate Plex2CSV into the webtools bundle, and when/if this happens, then this would be on the list for sure.

In the mean time, take a peak @ the files *fields.py

/T
