### ISSUE TITLE
Error when trying to export

### ISSUE THREAD

**Issue by tpetersheim** [ukdtom/plex2csv.bundle#97]
I get these logs trying to export. 

[com.plexapp.plugins.Plex2csv_2.txt](https://github.com/ukdtom/plex2csv.bundle/files/100164/com.plexapp.plugins.Plex2csv_2.txt)

**Comment by ukdtom** [comment]
Did you specify an export path in the settings?
And if so, remember to switch off AutoPath

**Comment by tpetersheim** [comment]
I left the export path as none and have the auto path option checked.

**Comment by ukdtom** [comment]
Try for a short test, and define it manually, and uncheck the autopath combo

Sadly seen a few cases, where it didn't work :-(

**Comment by tpetersheim** [comment]
I was able to get that to work.  I set the path to C:\plex\ and tried again.  It created the Plex2csv subfolder but still failed.  I rebooted the server and tried again and then it worked fine.  Thanks!

**Comment by ukdtom** [comment]
Strange, but cool that it worked in the end...
